version: '3.8'

services:
  api:
    container_name: "${SERVICE_NAME}-api"
    build:
      context: ./../..
      dockerfile: ./deployment/local/Dockerfile
    command: " ./main -api"
    restart: always
    env_file:
      - ./.env
    ports:
      - "8083:8083"
#    depends_on:
#      - kafka
    networks:
      - default


networks:
  default:
    driver: bridge
