version: '3.8'

services:
  api:
    container_name: "${SERVICE_NAME}-api"
    build:
      context: ./../..
      dockerfile: ./deployment/local/Dockerfile
    command: " ./main"
    restart: always
    env_file:
      - ./.env
    ports:
      - "8083:8083"
#    depends_on:
#      - kafka
    networks:
      - default

  mongodb:
    container_name: "${SERVICE_NAME}-mongo"
    image: "mongo:4.2.16-bionic"
    environment:
      - MONGO_DATABASE=${MONGO_DB}
      - MONGO_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
