version: '3.8'

services:
  api:
    container_name: "${SERVICE_NAME}-api"
    build:
      context: ./../..
      dockerfile: ./deployment/local/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "8083:8083"
    depends_on:
     mongodb:
        condition: service_healthy
#    networks:
#      - default

  mongodb:
    container_name: "${SERVICE_NAME}-mongo"
    image: mongo:latest
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 1s
      retries: 10
    environment:
#      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "27717:27017"
    volumes:
      - mongodb_data_container:/data/db
#    networks:
#      - default

  redis:
    image: redis:latest
    container_name: "${SERVICE_NAME}-redis"
    ports:
      - "6479:6379"
    restart: unless-stopped
#    networks:
#      - default

volumes:
  mongodb_data_container:


#networks:
#  default:
#    driver: bridge